apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poc-processor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "poc-processor.name" . }}
    helm.sh/chart: {{ include "poc-processor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "poc-processor.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "poc-processor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port | default 8080 }}
              protocol: TCP
          env:
            - name: "KAFKA_BOOTSTRAP_SERVERS"
              value: "{{ .Values.kafka.bootstrapServers }}"
            - name: "MONGO_HOST"
              value: "{{ .Values.mongo.host }}"
            - name: "MONGO_PORT"
              value: "{{ .Values.mongo.port }}"
          resources:
      serviceAccountName: {{ include "poc-processor.fullname" . }}