{{- if .Values.ingress.enabled -}}
{{- $fullName := include "poc-processor.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "poc-processor.name" . }}
    helm.sh/chart: {{ include "poc-processor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  backend:
    serviceName: {{ $fullName }}
    servicePort: 80
{{- end }}
