apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "poc-processor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "poc-processor.name" . }}
    helm.sh/chart: {{ include "poc-processor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - pods
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]