apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "poc-api.name" . }}
    helm.sh/chart: {{ include "poc-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: http
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.http)))}}
    nodePort: {{ .Values.service.nodePorts.http }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "poc-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
